apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: hello-spencer
  name: hello-spencer
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      run: hello-spencer
  template:
    metadata:
      labels:
        run: hello-spencer
    spec:
      containers:
      - image: docker.io/wkorando/hello-spencer:dev3
        name: hello-spencer
      terminationGracePeriodSeconds: 30
---
kind: Service
apiVersion: v1
metadata:
  labels:
    run: hello-spencer
  name: hello-spencer-port
  namespace: default
spec:
  selector:
    run: hello-spencer
  ports:
    - port: 8080
      name: http
  type: LoadBalancer
